// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_tracking/test/features/mainLayout/tabs/profile/presentation/viewModel/profile_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i12;

import 'package:flowery_tracking/core/errors/api_results.dart' as _i4;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/requestes/edit_profile_request_entity.dart'
    as _i9;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/Responses/driver_profile_response_entity.dart'
    as _i5;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/Responses/edit_profile_response_entity.dart'
    as _i8;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/Responses/upload_photo_response_entity.dart'
    as _i11;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/Responses/vehicle_response_entity.dart'
    as _i14;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/use_cases/edit_profile_use_case.dart'
    as _i7;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/use_cases/get_logged_user_use_case.dart'
    as _i2;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/use_cases/get_vehicle_use_case.dart'
    as _i13;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/use_cases/upload_photo_use_case.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetLoggedUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLoggedUserUseCase extends _i1.Mock
    implements _i2.GetLoggedUserUseCase {
  MockGetLoggedUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.DriverProfileResponseEntity>> invoke() =>
      (super.noSuchMethod(
            Invocation.method(#invoke, []),
            returnValue:
                _i3.Future<
                  _i4.ApiResult<_i5.DriverProfileResponseEntity>
                >.value(
                  _i6.dummyValue<
                    _i4.ApiResult<_i5.DriverProfileResponseEntity>
                  >(this, Invocation.method(#invoke, [])),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.DriverProfileResponseEntity>>);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i7.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i8.EditProfileResponseEntity>> invoke(
    _i9.EditProfileRequestEntity? editProfileRequestEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [editProfileRequestEntity]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i8.EditProfileResponseEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i8.EditProfileResponseEntity>>(
                    this,
                    Invocation.method(#invoke, [editProfileRequestEntity]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i8.EditProfileResponseEntity>>);
}

/// A class which mocks [UploadPhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadPhotoUseCase extends _i1.Mock
    implements _i10.UploadPhotoUseCase {
  MockUploadPhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i11.UploadPhotoResponseEntity>> invoke(
    _i12.File? imageFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [imageFile]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i11.UploadPhotoResponseEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i11.UploadPhotoResponseEntity>>(
                    this,
                    Invocation.method(#invoke, [imageFile]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i11.UploadPhotoResponseEntity>>);
}

/// A class which mocks [GetVehicleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVehicleUseCase extends _i1.Mock implements _i13.GetVehicleUseCase {
  MockGetVehicleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i14.VehicleResponseEntity>> invoke(
    String? vehicleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [vehicleId]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i14.VehicleResponseEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i14.VehicleResponseEntity>>(
                    this,
                    Invocation.method(#invoke, [vehicleId]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i14.VehicleResponseEntity>>);
}
