// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_tracking/test/features/auth/data/repositories/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dio/dio.dart' as _i27;
import 'package:flowery_tracking/core/errors/api_results.dart' as _i10;
import 'package:flowery_tracking/features/auth/api/client/auth_api_service.dart'
    as _i22;
import 'package:flowery_tracking/features/auth/api/model/forgetPassword/request/forget_password_request.dart'
    as _i24;
import 'package:flowery_tracking/features/auth/api/model/forgetPassword/request/reset_password_request.dart'
    as _i26;
import 'package:flowery_tracking/features/auth/api/model/forgetPassword/request/verify_reset_code_request.dart'
    as _i25;
import 'package:flowery_tracking/features/auth/api/model/forgetPassword/response/forget_password_response_dto.dart'
    as _i4;
import 'package:flowery_tracking/features/auth/api/model/forgetPassword/response/reset_password_response_dto.dart'
    as _i6;
import 'package:flowery_tracking/features/auth/api/model/forgetPassword/response/verify_reset_code_response_dto.dart'
    as _i5;
import 'package:flowery_tracking/features/auth/api/model/signIn/request/sign_in_request_dto.dart'
    as _i23;
import 'package:flowery_tracking/features/auth/api/model/signIn/response/sign_in_response_dto.dart'
    as _i3;
import 'package:flowery_tracking/features/auth/api/model/signUp/request/sign_up_request_model.dart'
    as _i20;
import 'package:flowery_tracking/features/auth/api/model/signUp/response/vehicle/vehicle_types_response_model.dart'
    as _i7;
import 'package:flowery_tracking/features/auth/data/dataSources/auth_local_data_source.dart'
    as _i21;
import 'package:flowery_tracking/features/auth/data/dataSources/auth_remote_data_source.dart'
    as _i8;
import 'package:flowery_tracking/features/auth/domain/entity/forgetPassword/request/forget_password_request_entity.dart'
    as _i15;
import 'package:flowery_tracking/features/auth/domain/entity/forgetPassword/request/reset_password_request_entity.dart'
    as _i19;
import 'package:flowery_tracking/features/auth/domain/entity/forgetPassword/request/verify_reset_code_request_entity.dart'
    as _i17;
import 'package:flowery_tracking/features/auth/domain/entity/forgetPassword/response/forget_password_response_entity.dart'
    as _i14;
import 'package:flowery_tracking/features/auth/domain/entity/forgetPassword/response/reset_password_response_entity.dart'
    as _i18;
import 'package:flowery_tracking/features/auth/domain/entity/forgetPassword/response/verify_reset_code_response_entity.dart'
    as _i16;
import 'package:flowery_tracking/features/auth/domain/entity/signIn/sign_in_request_entity.dart'
    as _i12;
import 'package:flowery_tracking/features/auth/domain/entity/signIn/sign_in_response_entity.dart'
    as _i11;
import 'package:flowery_tracking/features/auth/domain/entity/signUp/vehicle_type_entity.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVehicleTypesResponsEntity_0 extends _i1.SmartFake
    implements _i2.VehicleTypesResponsEntity {
  _FakeVehicleTypesResponsEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignInResponseDto_1 extends _i1.SmartFake
    implements _i3.SignInResponseDto {
  _FakeSignInResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVehicleTypesResponseDto_5 extends _i1.SmartFake
    implements _i7.VehicleTypesResponseDto {
  _FakeVehicleTypesResponseDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i8.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.ApiResult<_i11.SignInResponseEntity>> signIn({
    required _i12.SignInRequestEntity? requestEntity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {#requestEntity: requestEntity}),
            returnValue:
                _i9.Future<_i10.ApiResult<_i11.SignInResponseEntity>>.value(
                  _i13.dummyValue<_i10.ApiResult<_i11.SignInResponseEntity>>(
                    this,
                    Invocation.method(#signIn, [], {
                      #requestEntity: requestEntity,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i10.ApiResult<_i11.SignInResponseEntity>>);

  @override
  _i9.Future<_i10.ApiResult<_i14.ForgetPasswordResponseEntity>> forgetPassword(
    _i15.ForgetPasswordRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue:
                _i9.Future<
                  _i10.ApiResult<_i14.ForgetPasswordResponseEntity>
                >.value(
                  _i13.dummyValue<
                    _i10.ApiResult<_i14.ForgetPasswordResponseEntity>
                  >(this, Invocation.method(#forgetPassword, [request])),
                ),
          )
          as _i9.Future<_i10.ApiResult<_i14.ForgetPasswordResponseEntity>>);

  @override
  _i9.Future<_i10.ApiResult<_i16.VerifyResetCodeResponseEntity>>
  verifyResetCode(_i17.VerifyResetCodeRequestEntity? request) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue:
                _i9.Future<
                  _i10.ApiResult<_i16.VerifyResetCodeResponseEntity>
                >.value(
                  _i13.dummyValue<
                    _i10.ApiResult<_i16.VerifyResetCodeResponseEntity>
                  >(this, Invocation.method(#verifyResetCode, [request])),
                ),
          )
          as _i9.Future<_i10.ApiResult<_i16.VerifyResetCodeResponseEntity>>);

  @override
  _i9.Future<_i10.ApiResult<_i18.ResetPasswordResponseEntity>> resetPassword(
    _i19.ResetPasswordRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i9.Future<
                  _i10.ApiResult<_i18.ResetPasswordResponseEntity>
                >.value(
                  _i13.dummyValue<
                    _i10.ApiResult<_i18.ResetPasswordResponseEntity>
                  >(this, Invocation.method(#resetPassword, [request])),
                ),
          )
          as _i9.Future<_i10.ApiResult<_i18.ResetPasswordResponseEntity>>);

  @override
  _i9.Future<_i10.ApiResult<void>> signUp(
    _i20.SignUpRequestModel? signUpRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signUpRequest]),
            returnValue: _i9.Future<_i10.ApiResult<void>>.value(
              _i13.dummyValue<_i10.ApiResult<void>>(
                this,
                Invocation.method(#signUp, [signUpRequest]),
              ),
            ),
          )
          as _i9.Future<_i10.ApiResult<void>>);

  @override
  _i9.Future<_i10.ApiResult<_i2.VehicleTypesResponsEntity>> getVehicleTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleTypes, []),
            returnValue:
                _i9.Future<_i10.ApiResult<_i2.VehicleTypesResponsEntity>>.value(
                  _i13.dummyValue<
                    _i10.ApiResult<_i2.VehicleTypesResponsEntity>
                  >(this, Invocation.method(#getVehicleTypes, [])),
                ),
          )
          as _i9.Future<_i10.ApiResult<_i2.VehicleTypesResponsEntity>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i21.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.ApiResult<void>> writeToken({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#writeToken, [], {#token: token}),
            returnValue: _i9.Future<_i10.ApiResult<void>>.value(
              _i13.dummyValue<_i10.ApiResult<void>>(
                this,
                Invocation.method(#writeToken, [], {#token: token}),
              ),
            ),
          )
          as _i9.Future<_i10.ApiResult<void>>);

  @override
  _i9.Future<_i10.ApiResult<void>> setRememberMe({required bool? rememberMe}) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [], {#rememberMe: rememberMe}),
            returnValue: _i9.Future<_i10.ApiResult<void>>.value(
              _i13.dummyValue<_i10.ApiResult<void>>(
                this,
                Invocation.method(#setRememberMe, [], {
                  #rememberMe: rememberMe,
                }),
              ),
            ),
          )
          as _i9.Future<_i10.ApiResult<void>>);

  @override
  _i9.Future<bool> getRememberMe() =>
      (super.noSuchMethod(
            Invocation.method(#getRememberMe, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i2.VehicleTypesResponsEntity> loadVehicleList() =>
      (super.noSuchMethod(
            Invocation.method(#loadVehicleList, []),
            returnValue: _i9.Future<_i2.VehicleTypesResponsEntity>.value(
              _FakeVehicleTypesResponsEntity_0(
                this,
                Invocation.method(#loadVehicleList, []),
              ),
            ),
          )
          as _i9.Future<_i2.VehicleTypesResponsEntity>);
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i22.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.SignInResponseDto> signIn({
    required _i23.SignInRequestDto? requestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {#requestDto: requestDto}),
            returnValue: _i9.Future<_i3.SignInResponseDto>.value(
              _FakeSignInResponseDto_1(
                this,
                Invocation.method(#signIn, [], {#requestDto: requestDto}),
              ),
            ),
          )
          as _i9.Future<_i3.SignInResponseDto>);

  @override
  _i9.Future<_i4.ForgetPasswordResponseDto> forgetPassword(
    _i24.ForgetPasswordRequest? forgetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequest]),
            returnValue: _i9.Future<_i4.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_2(
                this,
                Invocation.method(#forgetPassword, [forgetPasswordRequest]),
              ),
            ),
          )
          as _i9.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i9.Future<_i5.VerifyResetCodeResponseDto> verifyResetCode(
    _i25.VerifyResetCodeRequest? verifyResetCodeRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequest]),
            returnValue: _i9.Future<_i5.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_3(
                this,
                Invocation.method(#verifyResetCode, [verifyResetCodeRequest]),
              ),
            ),
          )
          as _i9.Future<_i5.VerifyResetCodeResponseDto>);

  @override
  _i9.Future<_i6.ResetPasswordResponseDto> resetPassword(
    _i26.ResetPasswordRequest? resetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequest]),
            returnValue: _i9.Future<_i6.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_4(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequest]),
              ),
            ),
          )
          as _i9.Future<_i6.ResetPasswordResponseDto>);

  @override
  _i9.Future<void> signUp(_i27.FormData? formData) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [formData]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.VehicleTypesResponseDto> getVehicleTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleTypes, []),
            returnValue: _i9.Future<_i7.VehicleTypesResponseDto>.value(
              _FakeVehicleTypesResponseDto_5(
                this,
                Invocation.method(#getVehicleTypes, []),
              ),
            ),
          )
          as _i9.Future<_i7.VehicleTypesResponseDto>);
}
