// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_tracking/test/features/mainLayout/tabs/orders/api/dataSource/orders_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowery_tracking/features/mainLayout/tabs/orders/api/client/orders_api_service.dart'
    as _i4;
import 'package:flowery_tracking/features/mainLayout/tabs/orders/api/models/reponses/driver_orders_response_dto.dart'
    as _i2;
import 'package:flowery_tracking/features/mainLayout/tabs/orders/api/models/reponses/product_data_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDriverOrdersResponseDto_0 extends _i1.SmartFake
    implements _i2.DriverOrdersResponseDto {
  _FakeDriverOrdersResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDataDto_1 extends _i1.SmartFake
    implements _i3.ProductDataDto {
  _FakeProductDataDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrdersApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersApiService extends _i1.Mock implements _i4.OrdersApiService {
  MockOrdersApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DriverOrdersResponseDto> getDriverOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getDriverOrders, []),
            returnValue: _i5.Future<_i2.DriverOrdersResponseDto>.value(
              _FakeDriverOrdersResponseDto_0(
                this,
                Invocation.method(#getDriverOrders, []),
              ),
            ),
          )
          as _i5.Future<_i2.DriverOrdersResponseDto>);

  @override
  _i5.Future<_i3.ProductDataDto> getProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [productId]),
            returnValue: _i5.Future<_i3.ProductDataDto>.value(
              _FakeProductDataDto_1(
                this,
                Invocation.method(#getProduct, [productId]),
              ),
            ),
          )
          as _i5.Future<_i3.ProductDataDto>);
}
