// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3O2RTuMhFlqsGvPXqwK4TTFBnJJpPRE',
    appId: '1:1034210985533:web:5f6f26d2cbe3ce85e58c54',
    messagingSenderId: '1034210985533',
    projectId: 'flowery-rider-93523',
    authDomain: 'flowery-rider-93523.firebaseapp.com',
    storageBucket: 'flowery-rider-93523.firebasestorage.app',
    measurementId: 'G-C8DGSZG3D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyvCR5Yz_sEiNEkRXsydNMwTFL71coDY',
    appId: '1:1034210985533:android:e3ec22ad16db4569e58c54',
    messagingSenderId: '1034210985533',
    projectId: 'flowery-rider-93523',
    storageBucket: 'flowery-rider-93523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL7ozxym7qsXiDO0-4dNlcwJxhVml7K8I',
    appId: '1:1034210985533:ios:62f4e67e1416c38ce58c54',
    messagingSenderId: '1034210985533',
    projectId: 'flowery-rider-93523',
    storageBucket: 'flowery-rider-93523.firebasestorage.app',
    iosBundleId: 'com.example.floweryTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL7ozxym7qsXiDO0-4dNlcwJxhVml7K8I',
    appId: '1:1034210985533:ios:62f4e67e1416c38ce58c54',
    messagingSenderId: '1034210985533',
    projectId: 'flowery-rider-93523',
    storageBucket: 'flowery-rider-93523.firebasestorage.app',
    iosBundleId: 'com.example.floweryTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM3O2RTuMhFlqsGvPXqwK4TTFBnJJpPRE',
    appId: '1:1034210985533:web:292f002a5010c812e58c54',
    messagingSenderId: '1034210985533',
    projectId: 'flowery-rider-93523',
    authDomain: 'flowery-rider-93523.firebaseapp.com',
    storageBucket: 'flowery-rider-93523.firebasestorage.app',
    measurementId: 'G-L4E8CVH6EM',
  );
}
