// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_tracking/test/features/mainLayout/tabs/profile/api/dataSource/profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;

import 'package:flowery_tracking/features/mainLayout/tabs/profile/api/client/profile_api_service.dart'
    as _i5;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/api/model/requestes/edit_profile_request_model.dart'
    as _i7;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/api/model/responses/driver_profile_response_dto.dart'
    as _i2;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/api/model/responses/edit_profile_response_dto.dart'
    as _i3;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/api/model/responses/upload_photo_response_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDriverProfileResponseDto_0 extends _i1.SmartFake
    implements _i2.DriverProfileResponseDto {
  _FakeDriverProfileResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEditProfileResponseDto_1 extends _i1.SmartFake
    implements _i3.EditProfileResponseDto {
  _FakeEditProfileResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadPhotoResponseDto_2 extends _i1.SmartFake
    implements _i4.UploadPhotoResponseDto {
  _FakeUploadPhotoResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiService extends _i1.Mock implements _i5.ProfileApiService {
  MockProfileApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.DriverProfileResponseDto> getLoggedDriverData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedDriverData, []),
            returnValue: _i6.Future<_i2.DriverProfileResponseDto>.value(
              _FakeDriverProfileResponseDto_0(
                this,
                Invocation.method(#getLoggedDriverData, []),
              ),
            ),
          )
          as _i6.Future<_i2.DriverProfileResponseDto>);

  @override
  _i6.Future<_i3.EditProfileResponseDto> editProfile(
    _i7.EditProfileRequestModel? editProfileRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [editProfileRequestModel]),
            returnValue: _i6.Future<_i3.EditProfileResponseDto>.value(
              _FakeEditProfileResponseDto_1(
                this,
                Invocation.method(#editProfile, [editProfileRequestModel]),
              ),
            ),
          )
          as _i6.Future<_i3.EditProfileResponseDto>);

  @override
  _i6.Future<_i4.UploadPhotoResponseDto> uploadProfilePhoto(_i8.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [photo]),
            returnValue: _i6.Future<_i4.UploadPhotoResponseDto>.value(
              _FakeUploadPhotoResponseDto_2(
                this,
                Invocation.method(#uploadProfilePhoto, [photo]),
              ),
            ),
          )
          as _i6.Future<_i4.UploadPhotoResponseDto>);
}

/// A class which mocks [DriverProfileResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverProfileResponseDto extends _i1.Mock
    implements _i2.DriverProfileResponseDto {
  MockDriverProfileResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [EditProfileResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileResponseDto extends _i1.Mock
    implements _i3.EditProfileResponseDto {
  MockEditProfileResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [UploadPhotoResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadPhotoResponseDto extends _i1.Mock
    implements _i4.UploadPhotoResponseDto {
  MockUploadPhotoResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [EditProfileRequestModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileRequestModel extends _i1.Mock
    implements _i7.EditProfileRequestModel {
  MockEditProfileRequestModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
