// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_tracking/test/features/auth/presentation/viewModel/signin/sign_in_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_tracking/core/errors/api_results.dart' as _i4;
import 'package:flowery_tracking/features/auth/domain/entity/signIn/sign_in_request_entity.dart'
    as _i6;
import 'package:flowery_tracking/features/auth/domain/entity/signIn/sign_in_response_entity.dart'
    as _i5;
import 'package:flowery_tracking/features/auth/domain/use_cases/sign_in_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUseCase extends _i1.Mock implements _i2.SignInUseCase {
  MockSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.SignInResponseEntity>> invoke({
    required _i6.SignInRequestEntity? requestEntity,
    bool? rememberMeChecked = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [], {
              #requestEntity: requestEntity,
              #rememberMeChecked: rememberMeChecked,
            }),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.SignInResponseEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i5.SignInResponseEntity>>(
                    this,
                    Invocation.method(#invoke, [], {
                      #requestEntity: requestEntity,
                      #rememberMeChecked: rememberMeChecked,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.SignInResponseEntity>>);
}
