// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_tracking/test/features/mainLayout/tabs/profile/domain/use_cases/upload_photo_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i10;

import 'package:flowery_tracking/core/errors/api_results.dart' as _i4;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/requestes/edit_profile_request_entity.dart'
    as _i8;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/Responses/driver_profile_response_entity.dart'
    as _i5;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/Responses/edit_profile_response_entity.dart'
    as _i7;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/entity/Responses/upload_photo_response_entity.dart'
    as _i9;
import 'package:flowery_tracking/features/mainLayout/tabs/profile/domain/repositories/profile_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepo extends _i1.Mock implements _i2.ProfileRepo {
  MockProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.DriverProfileResponseEntity>>
  getLoggedDriverData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedDriverData, []),
            returnValue:
                _i3.Future<
                  _i4.ApiResult<_i5.DriverProfileResponseEntity>
                >.value(
                  _i6.dummyValue<
                    _i4.ApiResult<_i5.DriverProfileResponseEntity>
                  >(this, Invocation.method(#getLoggedDriverData, [])),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.DriverProfileResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.EditProfileResponseEntity>> editProfile(
    _i8.EditProfileRequestEntity? editProfileRequestEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [editProfileRequestEntity]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i7.EditProfileResponseEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i7.EditProfileResponseEntity>>(
                    this,
                    Invocation.method(#editProfile, [editProfileRequestEntity]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i7.EditProfileResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i9.UploadPhotoResponseEntity>> uploadProfilePhoto(
    _i10.File? imageFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [imageFile]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i9.UploadPhotoResponseEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i9.UploadPhotoResponseEntity>>(
                    this,
                    Invocation.method(#uploadProfilePhoto, [imageFile]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i9.UploadPhotoResponseEntity>>);
}
