default_platform(:android)
platform :android do
  desc "deploy a new version to firebase app distribution beta"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
    app: '1:1034210985533:android:e3ec22ad16db4569e58c54',
    firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
    android_artifact_type: "APK",
    apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
    testers: 'mizo201515@gmail.com',
    release_notes: 'New build available ^_^'
  )
  end
end
